In [1]:
import pandas as pd
import random
from datetime import datetime, timedelta

# -----------------------------
# CONFIG
# -----------------------------
NUM_STUDENTS = 10000
TESTS_PER_STUDENT = 3

subjects = ["Maths"]
topics = ["Algebra", "Geometry", "Trigonometry", "Mensuration", "Statistics"]

# -----------------------------
# 1. STUDENTS DATA
# -----------------------------
students = []

for i in range(1, NUM_STUDENTS + 1):
    students.append({
        "student_id": i,
        "name": f"Student_{i}",
        "class": random.choice([9, 10]),
        "board": random.choice(["CBSE", "SSC"])
    })

students_df = pd.DataFrame(students)

# -----------------------------
# 2. TESTS DATA
# -----------------------------
tests = []
test_id = 1

for student in students:
    for _ in range(TESTS_PER_STUDENT):
        total_marks = 100
        obtained_marks = random.randint(30, 95)
        time_taken = random.randint(30, 90)

        test_date = datetime.now() - timedelta(days=random.randint(0, 30))

        tests.append({
            "test_id": test_id,
            "student_id": student["student_id"],
            "subject": "Maths",
            "total_marks": total_marks,
            "obtained_marks": obtained_marks,
            "time_taken": time_taken,
            "test_date": test_date.strftime("%Y-%m-%d")
        })

        test_id += 1

tests_df = pd.DataFrame(tests)

# -----------------------------
# 3. TOPIC PERFORMANCE DATA
# -----------------------------
topic_data = []
topic_id = 1

for test in tests:
    for topic in topics:
        max_marks = 20
        obtained_marks = random.randint(5, 20)

        topic_data.append({
            "id": topic_id,
            "test_id": test["test_id"],
            "topic": topic,
            "max_marks": max_marks,
            "obtained_marks": obtained_marks
        })

        topic_id += 1

topic_df = pd.DataFrame(topic_data)

# -----------------------------
# SAVE FILES
# -----------------------------
students_df.to_csv("students.csv", index=False)
tests_df.to_csv("tests.csv", index=False)
topic_df.to_csv("topic_performance.csv", index=False)

print("✅ Data Generated Successfully!")

✅ Data Generated Successfully!

# Load Your Data

In [2]:
import pandas as pd

students=pd.read_csv("students.csv")
tests=pd.read_csv("tests.csv")
topics=pd.read_csv("topic_performance.csv")

## Merge Data

In [3]:
data=topics.merge(tests,on="test_id").merge(students,on="student_id")

In [6]:
data.head(20)

,id,test_id,topic,max_marks,obtained_marks_x,student_id,subject,total_marks,obtained_marks_y,time_taken,test_date,name,class,board
0,1,1,Algebra,20,9,1,Maths,100,94,55,2026-03-24,Student_1,10,CBSE
1,2,1,Geometry,20,16,1,Maths,100,94,55,2026-03-24,Student_1,10,CBSE
2,3,1,Trigonometry,20,10,1,Maths,100,94,55,2026-03-24,Student_1,10,CBSE
3,4,1,Mensuration,20,20,1,Maths,100,94,55,2026-03-24,Student_1,10,CBSE
4,5,1,Statistics,20,17,1,Maths,100,94,55,2026-03-24,Student_1,10,CBSE
5,6,2,Algebra,20,18,1,Maths,100,37,79,2026-03-31,Student_1,10,CBSE
6,7,2,Geometry,20,17,1,Maths,100,37,79,2026-03-31,Student_1,10,CBSE
7,8,2,Trigonometry,20,15,1,Maths,100,37,79,2026-03-31,Student_1,10,CBSE
8,9,2,Mensuration,20,6,1,Maths,100,37,79,2026-03-31,Student_1,10,CBSE
9,10,2,Statistics,20,12,1,Maths,100,37,79,2026-03-31,Student_1,10,CBSE
10,11,3,Algebra,20,8,1,Maths,100,54,51,2026-04-13,Student_1,10,CBSE
11,12,3,Geometry,20,14,1,Maths,100,54,51,2026-04-13,Student_1,10,CBSE
12,13,3,Trigonometry,20,8,1,Maths,100,54,51,2026-04-13,Student_1,10,CBSE
13,14,3,Mensuration,20,19,1,Maths,100,54,51,2026-04-13,Student_1,10,CBSE
14,15,3,Statistics,20,6,1,Maths,100,54,51,2026-04-13,Student_1,10,CBSE
15,16,4,Algebra,20,11,2,Maths,100,59,69,2026-03-30,Student_2,9,CBSE
16,17,4,Geometry,20,10,2,Maths,100,59,69,2026-03-30,Student_2,9,CBSE
17,18,4,Trigonometry,20,14,2,Maths,100,59,69,2026-03-30,Student_2,9,CBSE
18,19,4,Mensuration,20,10,2,Maths,100,59,69,2026-03-30,Student_2,9,CBSE
19,20,4,Statistics,20,15,2,Maths,100,59,69,2026-03-30,Student_2,9,CBSE

## Calculate Accuracy

In [7]:
data["accuracy"]=(data["obtained_marks_x"]/data["max_marks"]) *100

In [8]:
data.head(10)

,id,test_id,topic,max_marks,obtained_marks_x,student_id,subject,total_marks,obtained_marks_y,time_taken,test_date,name,class,board,accuracy
0,1,1,Algebra,20,9,1,Maths,100,94,55,2026-03-24,Student_1,10,CBSE,45.0
1,2,1,Geometry,20,16,1,Maths,100,94,55,2026-03-24,Student_1,10,CBSE,80.0
2,3,1,Trigonometry,20,10,1,Maths,100,94,55,2026-03-24,Student_1,10,CBSE,50.0
3,4,1,Mensuration,20,20,1,Maths,100,94,55,2026-03-24,Student_1,10,CBSE,100.0
4,5,1,Statistics,20,17,1,Maths,100,94,55,2026-03-24,Student_1,10,CBSE,85.0
5,6,2,Algebra,20,18,1,Maths,100,37,79,2026-03-31,Student_1,10,CBSE,90.0
6,7,2,Geometry,20,17,1,Maths,100,37,79,2026-03-31,Student_1,10,CBSE,85.0
7,8,2,Trigonometry,20,15,1,Maths,100,37,79,2026-03-31,Student_1,10,CBSE,75.0
8,9,2,Mensuration,20,6,1,Maths,100,37,79,2026-03-31,Student_1,10,CBSE,30.0
9,10,2,Statistics,20,12,1,Maths,100,37,79,2026-03-31,Student_1,10,CBSE,60.0

# Find Topic Performance Per Student

In [9]:
topic_summary=data.groupby(["student_id","topic"])["accuracy"].mean().reset_index()

In [10]:
data.head()

,id,test_id,topic,max_marks,obtained_marks_x,student_id,subject,total_marks,obtained_marks_y,time_taken,test_date,name,class,board,accuracy
0,1,1,Algebra,20,9,1,Maths,100,94,55,2026-03-24,Student_1,10,CBSE,45.0
1,2,1,Geometry,20,16,1,Maths,100,94,55,2026-03-24,Student_1,10,CBSE,80.0
2,3,1,Trigonometry,20,10,1,Maths,100,94,55,2026-03-24,Student_1,10,CBSE,50.0
3,4,1,Mensuration,20,20,1,Maths,100,94,55,2026-03-24,Student_1,10,CBSE,100.0
4,5,1,Statistics,20,17,1,Maths,100,94,55,2026-03-24,Student_1,10,CBSE,85.0

# Identify Weak & Strong Topics

In [12]:
def classify_topic(acc):
    if acc<50:
        return"Weak"
    elif acc>75:
        return"Strong"
    else:
        return "Average"

topic_summary["level"]=topic_summary["accuracy"].apply(classify_topic)

# Identify Slow Students

In [15]:
time_summary=tests.groupby("student_id")["time_taken"].mean().reset_index()

def classify_speed(time):
    if time > 70:
        return "slow"
    elif time<40:
        return "fast"
    else:
        return "Normal"
    
time_summary["speed"]=time_summary["time_taken"].apply(classify_speed)

# Recommendation Engine

In [16]:
def recommend(student_id):
    student_topics = topic_summary[topic_summary["student_id"] == student_id]
    student_speed = time_summary[time_summary["student_id"] == student_id]["speed"].values[0]

    weak = student_topics[student_topics["level"] == "Weak"]["topic"].tolist()
    strong = student_topics[student_topics["level"] == "Strong"]["topic"].tolist()

    print(f"\n📌 Recommendations for Student {student_id}:\n")

    if weak:
        print("🔴 Focus on weak topics:", ", ".join(weak))
        print("👉 Practice basic questions and revise concepts")

    if strong:
        print("\n🟢 Strong topics:", ", ".join(strong))
        print("👉 Try advanced questions")

    if student_speed == "Slow":
        print("\n⏱️ Work on speed: Take timed tests")

    elif student_speed == "Fast":
        print("\n⚡ Good speed: Try accuracy improvement")

    print("\n📚 Suggested Action: Attempt next test tomorrow")

In [20]:
recommend(10)

📌 Recommendations for Student 10:

🔴 Focus on weak topics: Trigonometry
👉 Practice basic questions and revise concepts

🟢 Strong topics: Geometry, Statistics
👉 Try advanced questions

📚 Suggested Action: Attempt next test tomorrow